apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ${node_class_name}
  namespace: ${namespace}
spec:
  role: ${node_role_name}
  amiFamily: ${ami_family}
  subnetSelectorTerms:
    - tags:
        ${discovery_tag_key}: ${discovery_tag_value}
  securityGroupSelectorTerms:
    - tags:
        ${discovery_tag_key}: ${discovery_tag_value}
  tags:
    ${discovery_tag_key}: ${discovery_tag_value} 